version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ${HOME}/docker_volumes/keycloak:/opt/keycloak/data/import
    command: [ "start-dev", "--import-realm" ]

  carservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carservice
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/carservice
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/auth/realms/CarServiceRealm
    depends_on:
      - mongodb
      - keycloak
    networks:
      - keycloak_network

networks:
  keycloak_network:

volumes:
  mongodb_data:
